# GITHUB ACTIONS
name: Homolog, Release

on: workflow_dispatch

# env:
#   IMAGE_NAME: ghtoken_product_demo

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # if: "$GITHUB_REF_NAME" == "develop"
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Log in to registry
        # This is where you will update the personal access token to GITHUB_TOKEN
        run: echo "${{ secrets.DEPLOY_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build images
        run: |
          docker build -t ghcr.io/$GITHUB_REPOSITORY:latest .

      - name: Push images
        run: |
          docker push ghcr.io/$GITHUB_REPOSITORY:latest

